'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3620
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Strings
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HK_GCS.Strings", GetType(Strings).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 2D Lock.
        '''</summary>
        Friend Shared ReadOnly Property _2D_Lock() As String
            Get
                Return ResourceManager.GetString("_2D_Lock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3D Lock.
        '''</summary>
        Friend Shared ReadOnly Property _3D_Lock() As String
            Get
                Return ResourceManager.GetString("_3D_Lock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3D Model.
        '''</summary>
        Friend Shared ReadOnly Property _3D_Model() As String
            Get
                Return ResourceManager.GetString("_3D_Model", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3D Models from OpenPilot Project.
        '''</summary>
        Friend Shared ReadOnly Property _3D_Models_From() As String
            Get
                Return ResourceManager.GetString("_3D_Models_From", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to About.
        '''</summary>
        Friend Shared ReadOnly Property About() As String
            Get
                Return ResourceManager.GetString("About", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;1 Accel.
        '''</summary>
        Friend Shared ReadOnly Property Accel_Mult() As String
            Get
                Return ResourceManager.GetString("Accel_Mult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Air Speed.
        '''</summary>
        Friend Shared ReadOnly Property Air_Speed() As String
            Get
                Return ResourceManager.GetString("Air_Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Air/Ground Speed.
        '''</summary>
        Friend Shared ReadOnly Property AirGround_Speed() As String
            Get
                Return ResourceManager.GetString("AirGround_Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;1 already exists.^Overwrite output file?.
        '''</summary>
        Friend Shared ReadOnly Property Already_Exists() As String
            Get
                Return ResourceManager.GetString("Already_Exists", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Altimeter.
        '''</summary>
        Friend Shared ReadOnly Property Altimeter() As String
            Get
                Return ResourceManager.GetString("Altimeter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Altitude Hold Mode.
        '''</summary>
        Friend Shared ReadOnly Property Altitude_Hold_Mode() As String
            Get
                Return ResourceManager.GetString("Altitude_Hold_Mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Altitude Offset.
        '''</summary>
        Friend Shared ReadOnly Property Altitude_Offset() As String
            Get
                Return ResourceManager.GetString("Altitude_Offset", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amperage Color.
        '''</summary>
        Friend Shared ReadOnly Property Amperage_Color() As String
            Get
                Return ResourceManager.GetString("Amperage_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Amps.
        '''</summary>
        Friend Shared ReadOnly Property Amps() As String
            Get
                Return ResourceManager.GetString("Amps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Danger! Danger! Signal lost for more than {alarm} seconds.
        '''</summary>
        Friend Shared ReadOnly Property Announce_Alarm_Default() As String
            Get
                Return ResourceManager.GetString("Announce_Alarm_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Announce Mode Change.
        '''</summary>
        Friend Shared ReadOnly Property Announce_ModeChange() As String
            Get
                Return ResourceManager.GetString("Announce_ModeChange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Changed mode to {mode}.
        '''</summary>
        Friend Shared ReadOnly Property Announce_ModeChange_Default() As String
            Get
                Return ResourceManager.GetString("Announce_ModeChange_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Announce Regular Interval.
        '''</summary>
        Friend Shared ReadOnly Property Announce_Regular_Interval() As String
            Get
                Return ResourceManager.GetString("Announce_Regular_Interval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to en route to waypoint {wpn}, altitude is {alt} feet, ground speed is {gsp} miles per hour.
        '''</summary>
        Friend Shared ReadOnly Property Announce_Regular_Interval_Default() As String
            Get
                Return ResourceManager.GetString("Announce_Regular_Interval_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Warning, Signal lost for {warning} seconds.
        '''</summary>
        Friend Shared ReadOnly Property Announce_Warning_Default() As String
            Get
                Return ResourceManager.GetString("Announce_Warning_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Announce Waypoints.
        '''</summary>
        Friend Shared ReadOnly Property Announce_Waypoints() As String
            Get
                Return ResourceManager.GetString("Announce_Waypoints", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Arrived, Now heading to waypoint {wpn}.
        '''</summary>
        Friend Shared ReadOnly Property Announce_Waypoints_Default() As String
            Get
                Return ResourceManager.GetString("Announce_Waypoints_Default", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to AP Mega Binary.
        '''</summary>
        Friend Shared ReadOnly Property AP_Mega_Binary() As String
            Get
                Return ResourceManager.GetString("AP_Mega_Binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ArduIMU Binary.
        '''</summary>
        Friend Shared ReadOnly Property ArduIMU_Binary() As String
            Get
                Return ResourceManager.GetString("ArduIMU_Binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to ArduPilot Message.
        '''</summary>
        Friend Shared ReadOnly Property ArduPilot_Message() As String
            Get
                Return ResourceManager.GetString("ArduPilot_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Assisted RC.
        '''</summary>
        Friend Shared ReadOnly Property Assisted_RC() As String
            Get
                Return ResourceManager.GetString("Assisted_RC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attitude.
        '''</summary>
        Friend Shared ReadOnly Property Attitude() As String
            Get
                Return ResourceManager.GetString("Attitude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Attitude Data.
        '''</summary>
        Friend Shared ReadOnly Property Attitude_Data() As String
            Get
                Return ResourceManager.GetString("Attitude_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Balance Mode.
        '''</summary>
        Friend Shared ReadOnly Property Auto_Balance_Mode() As String
            Get
                Return ResourceManager.GetString("Auto_Balance_Mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Auto Scroll.
        '''</summary>
        Friend Shared ReadOnly Property Auto_Scroll() As String
            Get
                Return ResourceManager.GetString("Auto_Scroll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Autonomous.
        '''</summary>
        Friend Shared ReadOnly Property Autonomous() As String
            Get
                Return ResourceManager.GetString("Autonomous", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Battery.
        '''</summary>
        Friend Shared ReadOnly Property Battery() As String
            Get
                Return ResourceManager.GetString("Battery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Battery &amp;&amp; Throttle.
        '''</summary>
        Friend Shared ReadOnly Property Battery_Throttle() As String
            Get
                Return ResourceManager.GetString("Battery_Throttle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Battery &amp;&amp; Throttle Settings.
        '''</summary>
        Friend Shared ReadOnly Property Battery_Throttle_Settings() As String
            Get
                Return ResourceManager.GetString("Battery_Throttle_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Baud Rate.
        '''</summary>
        Friend Shared ReadOnly Property Baud_Rate() As String
            Get
                Return ResourceManager.GetString("Baud_Rate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Blue.
        '''</summary>
        Friend Shared ReadOnly Property Blue() As String
            Get
                Return ResourceManager.GetString("Blue", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Building Map Files.
        '''</summary>
        Friend Shared ReadOnly Property Building_Map_Files() As String
            Get
                Return ResourceManager.GetString("Building_Map_Files", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cancel.
        '''</summary>
        Friend Shared ReadOnly Property Cancel() As String
            Get
                Return ResourceManager.GetString("Cancel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Carriage Return.
        '''</summary>
        Friend Shared ReadOnly Property Carriage_Return() As String
            Get
                Return ResourceManager.GetString("Carriage_Return", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Center On Plane.
        '''</summary>
        Friend Shared ReadOnly Property Center_On_Plane() As String
            Get
                Return ResourceManager.GetString("Center_On_Plane", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Change Model Scale.
        '''</summary>
        Friend Shared ReadOnly Property Change_Model_Scale() As String
            Get
                Return ResourceManager.GetString("Change_Model_Scale", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Channel Raw.
        '''</summary>
        Friend Shared ReadOnly Property Channel_Raw() As String
            Get
                Return ResourceManager.GetString("Channel_Raw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Chase Cam.
        '''</summary>
        Friend Shared ReadOnly Property Chase_Cam() As String
            Get
                Return ResourceManager.GetString("Chase_Cam", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Checking &amp;1 baud.
        '''</summary>
        Friend Shared ReadOnly Property Checking_baud() As String
            Get
                Return ResourceManager.GetString("Checking_baud", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Clear Map.
        '''</summary>
        Friend Shared ReadOnly Property Clear_Map() As String
            Get
                Return ResourceManager.GetString("Clear_Map", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to COM Port.
        '''</summary>
        Friend Shared ReadOnly Property COM_Port() As String
            Get
                Return ResourceManager.GetString("COM_Port", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Command Line.
        '''</summary>
        Friend Shared ReadOnly Property Command_Line() As String
            Get
                Return ResourceManager.GetString("Command_Line", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connect.
        '''</summary>
        Friend Shared ReadOnly Property Connect() As String
            Get
                Return ResourceManager.GetString("Connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Connected to &amp;1 at &amp;2.
        '''</summary>
        Friend Shared ReadOnly Property Connected_to() As String
            Get
                Return ResourceManager.GetString("Connected_to", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Culture.
        '''</summary>
        Friend Shared ReadOnly Property Current_Culture() As String
            Get
                Return ResourceManager.GetString("Current_Culture", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Current Waypoint.
        '''</summary>
        Friend Shared ReadOnly Property Current_Waypoint() As String
            Get
                Return ResourceManager.GetString("Current_Waypoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Custom Binary.
        '''</summary>
        Friend Shared ReadOnly Property Custom_Binary() As String
            Get
                Return ResourceManager.GetString("Custom_Binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cyan.
        '''</summary>
        Friend Shared ReadOnly Property Cyan() As String
            Get
                Return ResourceManager.GetString("Cyan", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data File.
        '''</summary>
        Friend Shared ReadOnly Property Data_File() As String
            Get
                Return ResourceManager.GetString("Data_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Data Points.
        '''</summary>
        Friend Shared ReadOnly Property Data_Points() As String
            Get
                Return ResourceManager.GetString("Data_Points", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Default Language.
        '''</summary>
        Friend Shared ReadOnly Property Default_Language() As String
            Get
                Return ResourceManager.GetString("Default_Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnect.
        '''</summary>
        Friend Shared ReadOnly Property Disconnect() As String
            Get
                Return ResourceManager.GetString("Disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Disconnected from &amp;1.
        '''</summary>
        Friend Shared ReadOnly Property Disconnect_from() As String
            Get
                Return ResourceManager.GetString("Disconnect_from", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distance.
        '''</summary>
        Friend Shared ReadOnly Property Distance() As String
            Get
                Return ResourceManager.GetString("Distance", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Distance Units.
        '''</summary>
        Friend Shared ReadOnly Property Distance_Units() As String
            Get
                Return ResourceManager.GetString("Distance_Units", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to down.
        '''</summary>
        Friend Shared ReadOnly Property Down() As String
            Get
                Return ResourceManager.GetString("Down", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Draw Full Mission.
        '''</summary>
        Friend Shared ReadOnly Property Draw_Full_Mission() As String
            Get
                Return ResourceManager.GetString("Draw_Full_Mission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error.
        '''</summary>
        Friend Shared ReadOnly Property Error_Message() As String
            Get
                Return ResourceManager.GetString("Error_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Exit.
        '''</summary>
        Friend Shared ReadOnly Property Exit_Label() As String
            Get
                Return ResourceManager.GetString("Exit_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Expand.
        '''</summary>
        Friend Shared ReadOnly Property Expand() As String
            Get
                Return ResourceManager.GetString("Expand", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Extrude.
        '''</summary>
        Friend Shared ReadOnly Property Extrude() As String
            Get
                Return ResourceManager.GetString("Extrude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Features.
        '''</summary>
        Friend Shared ReadOnly Property Features() As String
            Get
                Return ResourceManager.GetString("Features", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Feet.
        '''</summary>
        Friend Shared ReadOnly Property Feet() As String
            Get
                Return ResourceManager.GetString("Feet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to File.
        '''</summary>
        Friend Shared ReadOnly Property File() As String
            Get
                Return ResourceManager.GetString("File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to First Person.
        '''</summary>
        Friend Shared ReadOnly Property First_Person() As String
            Get
                Return ResourceManager.GetString("First_Person", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Flight Path Color.
        '''</summary>
        Friend Shared ReadOnly Property Flight_Path_Color() As String
            Get
                Return ResourceManager.GetString("Flight_Path_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Home Alt.
        '''</summary>
        Friend Shared ReadOnly Property From_HomeAlt() As String
            Get
                Return ResourceManager.GetString("From_HomeAlt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to From Sea Level.
        '''</summary>
        Friend Shared ReadOnly Property From_Sealevel() As String
            Get
                Return ResourceManager.GetString("From_Sealevel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Full.
        '''</summary>
        Friend Shared ReadOnly Property Full() As String
            Get
                Return ResourceManager.GetString("Full", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Borders.
        '''</summary>
        Friend Shared ReadOnly Property GE_Borders() As String
            Get
                Return ResourceManager.GetString("GE_Borders", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3D Buildings.
        '''</summary>
        Friend Shared ReadOnly Property GE_Buildings() As String
            Get
                Return ResourceManager.GetString("GE_Buildings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roads.
        '''</summary>
        Friend Shared ReadOnly Property GE_Roads() As String
            Get
                Return ResourceManager.GetString("GE_Roads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Terrain.
        '''</summary>
        Friend Shared ReadOnly Property GE_Terrain() As String
            Get
                Return ResourceManager.GetString("GE_Terrain", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 3D Trees.
        '''</summary>
        Friend Shared ReadOnly Property GE_Trees() As String
            Get
                Return ResourceManager.GetString("GE_Trees", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to General.
        '''</summary>
        Friend Shared ReadOnly Property General() As String
            Get
                Return ResourceManager.GetString("General", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Geonavigation Data.
        '''</summary>
        Friend Shared ReadOnly Property Geonavigation_Data() As String
            Get
                Return ResourceManager.GetString("Geonavigation_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Global Position.
        '''</summary>
        Friend Shared ReadOnly Property Global_Position() As String
            Get
                Return ResourceManager.GetString("Global_Position", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Google Earth.
        '''</summary>
        Friend Shared ReadOnly Property Google_Earth() As String
            Get
                Return ResourceManager.GetString("Google_Earth", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Google Earth Flight Path.
        '''</summary>
        Friend Shared ReadOnly Property Google_Earth_Flight_Path() As String
            Get
                Return ResourceManager.GetString("Google_Earth_Flight_Path", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPS Data.
        '''</summary>
        Friend Shared ReadOnly Property GPS_Data() As String
            Get
                Return ResourceManager.GetString("GPS_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPS Lock.
        '''</summary>
        Friend Shared ReadOnly Property GPS_Lock() As String
            Get
                Return ResourceManager.GetString("GPS_Lock", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPS Msg.
        '''</summary>
        Friend Shared ReadOnly Property GPS_Message() As String
            Get
                Return ResourceManager.GetString("GPS_Message", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPS Raw.
        '''</summary>
        Friend Shared ReadOnly Property GPS_Raw() As String
            Get
                Return ResourceManager.GetString("GPS_Raw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPS Status.
        '''</summary>
        Friend Shared ReadOnly Property GPS_Status() As String
            Get
                Return ResourceManager.GetString("GPS_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPS Time.
        '''</summary>
        Friend Shared ReadOnly Property GPS_Time() As String
            Get
                Return ResourceManager.GetString("GPS_Time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to GPS Type.
        '''</summary>
        Friend Shared ReadOnly Property GPS_Type() As String
            Get
                Return ResourceManager.GetString("GPS_Type", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Green.
        '''</summary>
        Friend Shared ReadOnly Property Green() As String
            Get
                Return ResourceManager.GetString("Green", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ground Control Station.
        '''</summary>
        Friend Shared ReadOnly Property Ground_Control_Station() As String
            Get
                Return ResourceManager.GetString("Ground_Control_Station", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Ground Speed.
        '''</summary>
        Friend Shared ReadOnly Property Ground_Speed() As String
            Get
                Return ResourceManager.GetString("Ground_Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;1 Gyro.
        '''</summary>
        Friend Shared ReadOnly Property Gyro_Mult() As String
            Get
                Return ResourceManager.GetString("Gyro_Mult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HappyKillmore&apos;s Email.
        '''</summary>
        Friend Shared ReadOnly Property HappyKillmores_Email() As String
            Get
                Return ResourceManager.GetString("HappyKillmores_Email", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to HDOP.
        '''</summary>
        Friend Shared ReadOnly Property HDOP() As String
            Get
                Return ResourceManager.GetString("HDOP", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heading.
        '''</summary>
        Friend Shared ReadOnly Property Heading() As String
            Get
                Return ResourceManager.GetString("Heading", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Heatbeat Data.
        '''</summary>
        Friend Shared ReadOnly Property Heatbeat_Data() As String
            Get
                Return ResourceManager.GetString("Heatbeat_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Help.
        '''</summary>
        Friend Shared ReadOnly Property Help() As String
            Get
                Return ResourceManager.GetString("Help", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Hertz.
        '''</summary>
        Friend Shared ReadOnly Property Hertz() As String
            Get
                Return ResourceManager.GetString("Hertz", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Highly Assisted.
        '''</summary>
        Friend Shared ReadOnly Property Highly_Assisted() As String
            Get
                Return ResourceManager.GetString("Highly_Assisted", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to In.
        '''</summary>
        Friend Shared ReadOnly Property In_Label() As String
            Get
                Return ResourceManager.GetString("In_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instrument Selection.
        '''</summary>
        Friend Shared ReadOnly Property Instrument_Selection() As String
            Get
                Return ResourceManager.GetString("Instrument_Selection", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Instruments.
        '''</summary>
        Friend Shared ReadOnly Property Instruments() As String
            Get
                Return ResourceManager.GetString("Instruments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Interval.
        '''</summary>
        Friend Shared ReadOnly Property Interval() As String
            Get
                Return ResourceManager.GetString("Interval", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid File.
        '''</summary>
        Friend Shared ReadOnly Property Invalid_File() As String
            Get
                Return ResourceManager.GetString("Invalid_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Mission File Format.
        '''</summary>
        Friend Shared ReadOnly Property Invalid_Mission_File_Format() As String
            Get
                Return ResourceManager.GetString("Invalid_Mission_File_Format", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Knots.
        '''</summary>
        Friend Shared ReadOnly Property Knots() As String
            Get
                Return ResourceManager.GetString("Knots", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to km/h.
        '''</summary>
        Friend Shared ReadOnly Property KPH() As String
            Get
                Return ResourceManager.GetString("KPH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Language.
        '''</summary>
        Friend Shared ReadOnly Property Language() As String
            Get
                Return ResourceManager.GetString("Language", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Latitude.
        '''</summary>
        Friend Shared ReadOnly Property Latitude() As String
            Get
                Return ResourceManager.GetString("Latitude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to L.
        '''</summary>
        Friend Shared ReadOnly Property Left() As String
            Get
                Return ResourceManager.GetString("Left", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line Feed.
        '''</summary>
        Friend Shared ReadOnly Property Line_Feed() As String
            Get
                Return ResourceManager.GetString("Line_Feed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Line Feed+Carriage Return.
        '''</summary>
        Friend Shared ReadOnly Property Line_Feed_Carriage_Return() As String
            Get
                Return ResourceManager.GetString("Line_Feed_Carriage_Return", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Live Camera.
        '''</summary>
        Friend Shared ReadOnly Property Live_Camera() As String
            Get
                Return ResourceManager.GetString("Live_Camera", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading COM Ports.
        '''</summary>
        Friend Shared ReadOnly Property Loading_COM_Ports() As String
            Get
                Return ResourceManager.GetString("Loading_COM_Ports", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loading Settings.
        '''</summary>
        Friend Shared ReadOnly Property Loading_Settings() As String
            Get
                Return ResourceManager.GetString("Loading_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Location Data.
        '''</summary>
        Friend Shared ReadOnly Property Location_Data() As String
            Get
                Return ResourceManager.GetString("Location_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Locked.
        '''</summary>
        Friend Shared ReadOnly Property Locked() As String
            Get
                Return ResourceManager.GetString("Locked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Loiter.
        '''</summary>
        Friend Shared ReadOnly Property Loiter() As String
            Get
                Return ResourceManager.GetString("Loiter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Longitude.
        '''</summary>
        Friend Shared ReadOnly Property Longitude() As String
            Get
                Return ResourceManager.GetString("Longitude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to m/s.
        '''</summary>
        Friend Shared ReadOnly Property m_s() As String
            Get
                Return ResourceManager.GetString("m_s", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &amp;1 Mag.
        '''</summary>
        Friend Shared ReadOnly Property Mag_Mult() As String
            Get
                Return ResourceManager.GetString("Mag_Mult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mAh.
        '''</summary>
        Friend Shared ReadOnly Property mAh() As String
            Get
                Return ResourceManager.GetString("mAh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mAh Color.
        '''</summary>
        Friend Shared ReadOnly Property MAH_Color() As String
            Get
                Return ResourceManager.GetString("MAH_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Manual Mode.
        '''</summary>
        Friend Shared ReadOnly Property Manual_Mode() As String
            Get
                Return ResourceManager.GetString("Manual_Mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map Update Rate.
        '''</summary>
        Friend Shared ReadOnly Property Map_Update_Rate() As String
            Get
                Return ResourceManager.GetString("Map_Update_Rate", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Map View.
        '''</summary>
        Friend Shared ReadOnly Property Map_View() As String
            Get
                Return ResourceManager.GetString("Map_View", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Amperage.
        '''</summary>
        Friend Shared ReadOnly Property Max_Amperage() As String
            Get
                Return ResourceManager.GetString("Max_Amperage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Attitude.
        '''</summary>
        Friend Shared ReadOnly Property Max_Attitude() As String
            Get
                Return ResourceManager.GetString("Max_Attitude", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max GPS.
        '''</summary>
        Friend Shared ReadOnly Property Max_GPS() As String
            Get
                Return ResourceManager.GetString("Max_GPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max mAh.
        '''</summary>
        Friend Shared ReadOnly Property Max_MAH() As String
            Get
                Return ResourceManager.GetString("Max_MAH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Speed.
        '''</summary>
        Friend Shared ReadOnly Property Max_Speed() As String
            Get
                Return ResourceManager.GetString("Max_Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Voltage.
        '''</summary>
        Friend Shared ReadOnly Property Max_Voltage() As String
            Get
                Return ResourceManager.GetString("Max_Voltage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Max Waypoint.
        '''</summary>
        Friend Shared ReadOnly Property Max_Waypoint() As String
            Get
                Return ResourceManager.GetString("Max_Waypoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Meters.
        '''</summary>
        Friend Shared ReadOnly Property Meters() As String
            Get
                Return ResourceManager.GetString("Meters", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to min.
        '''</summary>
        Friend Shared ReadOnly Property min() As String
            Get
                Return ResourceManager.GetString("min", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Min mAh.
        '''</summary>
        Friend Shared ReadOnly Property Min_MAH() As String
            Get
                Return ResourceManager.GetString("Min_MAH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Min Voltage.
        '''</summary>
        Friend Shared ReadOnly Property Min_Voltage() As String
            Get
                Return ResourceManager.GetString("Min_Voltage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to mins.
        '''</summary>
        Friend Shared ReadOnly Property mins() As String
            Get
                Return ResourceManager.GetString("mins", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mission.
        '''</summary>
        Friend Shared ReadOnly Property Mission() As String
            Get
                Return ResourceManager.GetString("Mission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mission Path.
        '''</summary>
        Friend Shared ReadOnly Property Mission_Path() As String
            Get
                Return ResourceManager.GetString("Mission_Path", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mission Path Color.
        '''</summary>
        Friend Shared ReadOnly Property Mission_Path_Color() As String
            Get
                Return ResourceManager.GetString("Mission_Path_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mode.
        '''</summary>
        Friend Shared ReadOnly Property Mode() As String
            Get
                Return ResourceManager.GetString("Mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mode Change.
        '''</summary>
        Friend Shared ReadOnly Property Mode_Change() As String
            Get
                Return ResourceManager.GetString("Mode_Change", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to MPH.
        '''</summary>
        Friend Shared ReadOnly Property MPH() As String
            Get
                Return ResourceManager.GetString("MPH", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No.
        '''</summary>
        Friend Shared ReadOnly Property No() As String
            Get
                Return ResourceManager.GetString("No", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No line ending.
        '''</summary>
        Friend Shared ReadOnly Property No_line_ending() As String
            Get
                Return ResourceManager.GetString("No_line_ending", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to No Tracking.
        '''</summary>
        Friend Shared ReadOnly Property No_Tracking() As String
            Get
                Return ResourceManager.GetString("No_Tracking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to None.
        '''</summary>
        Friend Shared ReadOnly Property None() As String
            Get
                Return ResourceManager.GetString("None", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Normal.
        '''</summary>
        Friend Shared ReadOnly Property Normal() As String
            Get
                Return ResourceManager.GetString("Normal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Not Locked.
        '''</summary>
        Friend Shared ReadOnly Property Not_Locked() As String
            Get
                Return ResourceManager.GetString("Not_Locked", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to OK.
        '''</summary>
        Friend Shared ReadOnly Property OK() As String
            Get
                Return ResourceManager.GetString("OK", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Download List.
        '''</summary>
        Friend Shared ReadOnly Property Open_Downloads() As String
            Get
                Return ResourceManager.GetString("Open_Downloads", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Open Project Homepage.
        '''</summary>
        Friend Shared ReadOnly Property Open_Homepage() As String
            Get
                Return ResourceManager.GetString("Open_Homepage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Orange.
        '''</summary>
        Friend Shared ReadOnly Property Orange() As String
            Get
                Return ResourceManager.GetString("Orange", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Original Instrument Code by Guillaume CHOUTEAU.
        '''</summary>
        Friend Shared ReadOnly Property Original_Instruments() As String
            Get
                Return ResourceManager.GetString("Original_Instruments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Out.
        '''</summary>
        Friend Shared ReadOnly Property Out_Label() As String
            Get
                Return ResourceManager.GetString("Out_Label", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overhead.
        '''</summary>
        Friend Shared ReadOnly Property Overhead() As String
            Get
                Return ResourceManager.GetString("Overhead", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Overwrite File.
        '''</summary>
        Friend Shared ReadOnly Property Overwrite_File() As String
            Get
                Return ResourceManager.GetString("Overwrite_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path Opacity.
        '''</summary>
        Friend Shared ReadOnly Property Path_Opacity() As String
            Get
                Return ResourceManager.GetString("Path_Opacity", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Path Thickness.
        '''</summary>
        Friend Shared ReadOnly Property Path_Thickness() As String
            Get
                Return ResourceManager.GetString("Path_Thickness", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pause.
        '''</summary>
        Friend Shared ReadOnly Property Pause() As String
            Get
                Return ResourceManager.GetString("Pause", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Pitch.
        '''</summary>
        Friend Shared ReadOnly Property Pitch() As String
            Get
                Return ResourceManager.GetString("Pitch", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Play.
        '''</summary>
        Friend Shared ReadOnly Property Play() As String
            Get
                Return ResourceManager.GetString("Play", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Project Homepage.
        '''</summary>
        Friend Shared ReadOnly Property Project_Homepage() As String
            Get
                Return ResourceManager.GetString("Project_Homepage", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Properties.
        '''</summary>
        Friend Shared ReadOnly Property Properties() As String
            Get
                Return ResourceManager.GetString("Properties", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Protocol.
        '''</summary>
        Friend Shared ReadOnly Property Protocol() As String
            Get
                Return ResourceManager.GetString("Protocol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Purple.
        '''</summary>
        Friend Shared ReadOnly Property Purple() As String
            Get
                Return ResourceManager.GetString("Purple", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raw Data.
        '''</summary>
        Friend Shared ReadOnly Property Raw_Data() As String
            Get
                Return ResourceManager.GetString("Raw_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Raw IMU.
        '''</summary>
        Friend Shared ReadOnly Property Raw_IMU() As String
            Get
                Return ResourceManager.GetString("Raw_IMU", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R/C Channels Scaled.
        '''</summary>
        Friend Shared ReadOnly Property RC_Channels_Scaled() As String
            Get
                Return ResourceManager.GetString("RC_Channels_Scaled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Record.
        '''</summary>
        Friend Shared ReadOnly Property Record() As String
            Get
                Return ResourceManager.GetString("Record", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Red.
        '''</summary>
        Friend Shared ReadOnly Property Red() As String
            Get
                Return ResourceManager.GetString("Red", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reload COM Port List.
        '''</summary>
        Friend Shared ReadOnly Property Reload_Com_Port_List() As String
            Get
                Return ResourceManager.GetString("Reload_Com_Port_List", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R.
        '''</summary>
        Friend Shared ReadOnly Property Reload_Letter() As String
            Get
                Return ResourceManager.GetString("Reload_Letter", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reload Mission.
        '''</summary>
        Friend Shared ReadOnly Property Reload_Mission() As String
            Get
                Return ResourceManager.GetString("Reload_Mission", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reload Mission Directory.
        '''</summary>
        Friend Shared ReadOnly Property Reload_Mission_Directory() As String
            Get
                Return ResourceManager.GetString("Reload_Mission_Directory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reload Output File List.
        '''</summary>
        Friend Shared ReadOnly Property Reload_Output_File_List() As String
            Get
                Return ResourceManager.GetString("Reload_Output_File_List", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reset Run Timer.
        '''</summary>
        Friend Shared ReadOnly Property Reset_Run_Timer() As String
            Get
                Return ResourceManager.GetString("Reset_Run_Timer", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Resizing Form.
        '''</summary>
        Friend Shared ReadOnly Property Resizing_Form() As String
            Get
                Return ResourceManager.GetString("Resizing_Form", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Return Home.
        '''</summary>
        Friend Shared ReadOnly Property Return_Home() As String
            Get
                Return ResourceManager.GetString("Return_Home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Reversed.
        '''</summary>
        Friend Shared ReadOnly Property Reversed() As String
            Get
                Return ResourceManager.GetString("Reversed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Rewind to Beginning.
        '''</summary>
        Friend Shared ReadOnly Property Rewind_To_Beginning() As String
            Get
                Return ResourceManager.GetString("Rewind_To_Beginning", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to R.
        '''</summary>
        Friend Shared ReadOnly Property Right() As String
            Get
                Return ResourceManager.GetString("Right", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Roll.
        '''</summary>
        Friend Shared ReadOnly Property Roll() As String
            Get
                Return ResourceManager.GetString("Roll", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Run Time.
        '''</summary>
        Friend Shared ReadOnly Property Run_Time() As String
            Get
                Return ResourceManager.GetString("Run_Time", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Satellites.
        '''</summary>
        Friend Shared ReadOnly Property Satellites() As String
            Get
                Return ResourceManager.GetString("Satellites", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save.
        '''</summary>
        Friend Shared ReadOnly Property Save() As String
            Get
                Return ResourceManager.GetString("Save", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search Baud.
        '''</summary>
        Friend Shared ReadOnly Property Search_Baud() As String
            Get
                Return ResourceManager.GetString("Search_Baud", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Search COM.
        '''</summary>
        Friend Shared ReadOnly Property Search_COM() As String
            Get
                Return ResourceManager.GetString("Search_COM", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to sec.
        '''</summary>
        Friend Shared ReadOnly Property sec() As String
            Get
                Return ResourceManager.GetString("sec", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to secs.
        '''</summary>
        Friend Shared ReadOnly Property secs() As String
            Get
                Return ResourceManager.GetString("secs", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Select Data File Directory.
        '''</summary>
        Friend Shared ReadOnly Property Select_Data_File_Directory() As String
            Get
                Return ResourceManager.GetString("Select_Data_File_Directory", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Send.
        '''</summary>
        Friend Shared ReadOnly Property Send() As String
            Get
                Return ResourceManager.GetString("Send", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sensors.
        '''</summary>
        Friend Shared ReadOnly Property Sensors() As String
            Get
                Return ResourceManager.GetString("Sensors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serial Data.
        '''</summary>
        Friend Shared ReadOnly Property Serial_Data() As String
            Get
                Return ResourceManager.GetString("Serial_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Serial Settings.
        '''</summary>
        Friend Shared ReadOnly Property Serial_Settings() As String
            Get
                Return ResourceManager.GetString("Serial_Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Servo &amp;1.
        '''</summary>
        Friend Shared ReadOnly Property Servo_Mult() As String
            Get
                Return ResourceManager.GetString("Servo_Mult", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Servos.
        '''</summary>
        Friend Shared ReadOnly Property Servos() As String
            Get
                Return ResourceManager.GetString("Servos", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Set Home.
        '''</summary>
        Friend Shared ReadOnly Property Set_Home() As String
            Get
                Return ResourceManager.GetString("Set_Home", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setting up Comboboxes.
        '''</summary>
        Friend Shared ReadOnly Property Setting_Up_Comboboxes() As String
            Get
                Return ResourceManager.GetString("Setting_Up_Comboboxes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Setting up Webbrowser.
        '''</summary>
        Friend Shared ReadOnly Property Setting_Up_Webbrowser() As String
            Get
                Return ResourceManager.GetString("Setting_Up_Webbrowser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Settings.
        '''</summary>
        Friend Shared ReadOnly Property Settings() As String
            Get
                Return ResourceManager.GetString("Settings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Shrink.
        '''</summary>
        Friend Shared ReadOnly Property Shrink() As String
            Get
                Return ResourceManager.GetString("Shrink", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Socket Num.
        '''</summary>
        Friend Shared ReadOnly Property Socket_Num() As String
            Get
                Return ResourceManager.GetString("Socket_Num", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speech.
        '''</summary>
        Friend Shared ReadOnly Property Speech() As String
            Get
                Return ResourceManager.GetString("Speech", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speed.
        '''</summary>
        Friend Shared ReadOnly Property Speed() As String
            Get
                Return ResourceManager.GetString("Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Speed Units.
        '''</summary>
        Friend Shared ReadOnly Property Speed_Units() As String
            Get
                Return ResourceManager.GetString("Speed_Units", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stabilized.
        '''</summary>
        Friend Shared ReadOnly Property Stabilized() As String
            Get
                Return ResourceManager.GetString("Stabilized", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Starting &amp;1.
        '''</summary>
        Friend Shared ReadOnly Property Starting_GCS() As String
            Get
                Return ResourceManager.GetString("Starting_GCS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Status.
        '''</summary>
        Friend Shared ReadOnly Property Status() As String
            Get
                Return ResourceManager.GetString("Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Step Back.
        '''</summary>
        Friend Shared ReadOnly Property Step_Back() As String
            Get
                Return ResourceManager.GetString("Step_Back", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Step Forward.
        '''</summary>
        Friend Shared ReadOnly Property Step_Forward() As String
            Get
                Return ResourceManager.GetString("Step_Forward", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Stop Recording.
        '''</summary>
        Friend Shared ReadOnly Property Stop_Recording() As String
            Get
                Return ResourceManager.GetString("Stop_Recording", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Supported Protocols.
        '''</summary>
        Friend Shared ReadOnly Property Supported_Protocols() As String
            Get
                Return ResourceManager.GetString("Supported_Protocols", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to System Status.
        '''</summary>
        Friend Shared ReadOnly Property System_Status() As String
            Get
                Return ResourceManager.GetString("System_Status", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Target Alt.
        '''</summary>
        Friend Shared ReadOnly Property Target_Alt() As String
            Get
                Return ResourceManager.GetString("Target_Alt", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Telemetry GPS.
        '''</summary>
        Friend Shared ReadOnly Property Telemetry_GPS() As String
            Get
                Return ResourceManager.GetString("Telemetry_GPS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Thro.
        '''</summary>
        Friend Shared ReadOnly Property Thro() As String
            Get
                Return ResourceManager.GetString("Thro", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Throttle.
        '''</summary>
        Friend Shared ReadOnly Property Throttle() As String
            Get
                Return ResourceManager.GetString("Throttle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Throttle Channel.
        '''</summary>
        Friend Shared ReadOnly Property Throttle_Channel() As String
            Get
                Return ResourceManager.GetString("Throttle_Channel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Throttle Color.
        '''</summary>
        Friend Shared ReadOnly Property Throttle_Color() As String
            Get
                Return ResourceManager.GetString("Throttle_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Tracking.
        '''</summary>
        Friend Shared ReadOnly Property Tracking() As String
            Get
                Return ResourceManager.GetString("Tracking", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Translated Data.
        '''</summary>
        Friend Shared ReadOnly Property Translated_Data() As String
            Get
                Return ResourceManager.GetString("Translated_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Turn Coordinator.
        '''</summary>
        Friend Shared ReadOnly Property Turn_Coordinator() As String
            Get
                Return ResourceManager.GetString("Turn_Coordinator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type F13.
        '''</summary>
        Friend Shared ReadOnly Property Type_F13() As String
            Get
                Return ResourceManager.GetString("Type_F13", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to uBlox Binary.
        '''</summary>
        Friend Shared ReadOnly Property uBlox_Binary() As String
            Get
                Return ResourceManager.GetString("uBlox_Binary", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to up.
        '''</summary>
        Friend Shared ReadOnly Property Up() As String
            Get
                Return ResourceManager.GetString("Up", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to UTC.
        '''</summary>
        Friend Shared ReadOnly Property UTC() As String
            Get
                Return ResourceManager.GetString("UTC", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Version.
        '''</summary>
        Friend Shared ReadOnly Property Version() As String
            Get
                Return ResourceManager.GetString("Version", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Vertical Speed.
        '''</summary>
        Friend Shared ReadOnly Property Vertical_Speed() As String
            Get
                Return ResourceManager.GetString("Vertical_Speed", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to View File.
        '''</summary>
        Friend Shared ReadOnly Property View_File() As String
            Get
                Return ResourceManager.GetString("View_File", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voice.
        '''</summary>
        Friend Shared ReadOnly Property Voice() As String
            Get
                Return ResourceManager.GetString("Voice", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Voltage Color.
        '''</summary>
        Friend Shared ReadOnly Property Voltage_Color() As String
            Get
                Return ResourceManager.GetString("Voltage_Color", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Volts.
        '''</summary>
        Friend Shared ReadOnly Property Volts() As String
            Get
                Return ResourceManager.GetString("Volts", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waypoint.
        '''</summary>
        Friend Shared ReadOnly Property Waypoint() As String
            Get
                Return ResourceManager.GetString("Waypoint", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waypoint Data.
        '''</summary>
        Friend Shared ReadOnly Property Waypoint_Data() As String
            Get
                Return ResourceManager.GetString("Waypoint_Data", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Waypoint Mode.
        '''</summary>
        Friend Shared ReadOnly Property Waypoint_Mode() As String
            Get
                Return ResourceManager.GetString("Waypoint_Mode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yaw.
        '''</summary>
        Friend Shared ReadOnly Property Yaw() As String
            Get
                Return ResourceManager.GetString("Yaw", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yellow.
        '''</summary>
        Friend Shared ReadOnly Property Yellow() As String
            Get
                Return ResourceManager.GetString("Yellow", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Yes.
        '''</summary>
        Friend Shared ReadOnly Property Yes() As String
            Get
                Return ResourceManager.GetString("Yes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Zero Yaw.
        '''</summary>
        Friend Shared ReadOnly Property Zero_Yaw() As String
            Get
                Return ResourceManager.GetString("Zero_Yaw", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
