'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class TextFiles
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HK_GCS_Lite.TextFiles", GetType(TextFiles).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // Auto Copter modes
        '''// ----------------
        '''Stabilize,100,0
        '''Acrobatic,101,0
        '''Simple,102,0
        '''Altitude Hold,103,0
        '''Auto - Mission,4,3
        '''Guided - Loiter,3,2
        '''Auto - Loiter,4,8
        '''Auto - Return to Launch,4,5
        '''.
        '''</summary>
        Friend Shared ReadOnly Property ACMModes() As String
            Get
                Return ResourceManager.GetString("ACMModes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // Command IDs
        '''// (Tool Tip comment),[Unit],{ComboBox Options with Semi Colons},&lt;Multiplier&gt;,~Format~
        '''//16,Waypoint,Hold Time ~0.0~,Radius [m] ~0.00~ (Acceptance radius - if the sphere with this radius is hit the waypoint counts as reached),,,Latitude,Longitude,Altitude [m] ~0.00~
        '''16,Waypoint,,,,,Latitude,Longitude,Altitude [m] ~0.00~
        '''//17,Loiter,,,Radius [m] ~0.00~ (Radius around waypoint. If positive loiter clockwise else counter-clockwise),,Latitude,Longitude,Altitude [m] ~0.00~
        '''//18,Loiter Turns,Tu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property APMCommands() As String
            Get
                Return ResourceManager.GetString("APMCommands", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // Auto Pilot modes
        '''// ----------------
        '''Manual,2,0
        '''Guided - Take-off,3,1
        '''Guided - Loiter,3,2
        '''Guided - Landing,3,6
        '''Stabilize,5,0
        '''Fly By Wire A,6,1
        '''Fly By Wire B,6,2
        '''Fly By Wire C,6,3
        '''Auto - Mission,4,3
        '''Auto - Return to Launch,4,5
        '''Auto - Loiter,4,8
        '''//Takeoff 13
        '''//Land 14
        '''//Waypoint 16
        '''//Circle,1
        '''.
        '''</summary>
        Friend Shared ReadOnly Property APMModes() As String
            Get
                Return ResourceManager.GetString("APMModes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //EEPROM variable name,Min,Max,Default,Multiplier,Enabled (0 = no, 1 = yes),Comment
        '''MAH,,,,,1,
        '''CURRENT_ENABLE,,,,,1,
        '''AOA,,,,,1,
        '''MAG_ENABLE,,,,,1,
        '''HDNG2RLL_P,0,5,0.7,1,1,NAV_ROLL_P - Navigation control gains, Tuning values for the navigation control PID loops, The P term is the primary tuning value.  This determines how the control deflection varies in proportion to the required correction.
        '''HDNG2RLL_I,0,1,0.01,1,1,NAV_ROLL_I - Navigation control gains, Tuning values for the navigation control PID loops [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property APMSetConfig() As String
            Get
                Return ResourceManager.GetString("APMSetConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to $1,Mix Enable,0,1,0,Enable flag for Elevon/V-tail mixing. 0 = FALSE, 1 = TRUE
        '''$2,Mix Servo1 Sign,-1,1,1,If Mixing for Elevon/V-tail is enabled, this is Elevon 1 servo direction
        '''$3,Mix Servo2 Sign,-1,1,1,If Mixing for Elevon/V-tail is enabled, this is Elevon 2 servo direction
        '''$4,Servo 1 Gain,0,100,10,Is 10x format. Aileron, or with elevons it is the aileron component of the mix
        '''$5,Servo 2 Gain,0,100,10,Is 10x format. Elevator, or with elevons it is the elevator component of the mix
        '''$6,Servo 3 Gain,0,100 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property AttoSetConfig() As String
            Get
                Return ResourceManager.GetString("AttoSetConfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // Command IDs
        '''// (Tool Tip comment),[Unit],{ComboBox Options with Semi Colons},&lt;Multiplier&gt;,~Format~
        '''0,Empty
        '''1,Climb,Climb To [m] ~0.00~
        '''2,From to Relative,Circle Center (North) [m] ~0.00~,Circle Center (East) [m] ~0.00~,Circle Radius [m] ~0.00~,Height [m] ~0.00~
        '''3,From to Absolute,Latitude,Longitude,Altitude
        '''4,Fly to Relative,Distance (North) [m] ~0.00~,Distance (East) [m] ~0.00~,Altitude [m] ~0.00~
        '''5,Fly to Absolute,Latitude,Longitude,Altitude [m] ~0.00~
        '''6,Goto Line,Line Number
        '''7,Circle Absolute [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GluonCommands() As String
            Get
                Return ResourceManager.GetString("GluonCommands", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //Arg Number,Name,Min,Max,Default,Mult,Add,Bit,Desc
        '''1,acc_x_neutral,,,,1,0,,
        '''2,acc_y_neutral,,,,1,0,,
        '''3,acc_z_neutral,,,,1,0,,
        '''4,gyro_x_neutral,,,,1,0,,
        '''5,gyro_y_neutral,,,,1,0,,
        '''6,gyro_z_neutral,,,,1,0,,
        '''
        '''7,telemetry_basicgps,0,10,,1,0,,
        '''8,telemetry_ppm,0,10,,1,0,,
        '''9,telemetry_gyroaccraw,0,10,,1,0,,
        '''10,telemetry_gyroaccproc,0,10,,1,0,,
        '''11,telemetry_pressuretemp,0,10,,1,0,,
        '''12,telemetry_attitude,0,10,,1,0,,
        '''
        '''13,gps_initial_baudrate,,,,10,0,,
        '''14,gps_operational_baudrate,,,,10,0,,
        '''
        '''15,channe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend Shared ReadOnly Property GluonSetConfig() As String
            Get
                Return ResourceManager.GetString("GluonSetConfig", resourceCulture)
            End Get
        End Property
    End Class
End Namespace
