'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5446
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AvionicsInstrumentsControlsRessources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HK_GCS_Lite.AvionicsInstrumentsControlsRessources", GetType(AvionicsInstrumentsControlsRessources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property _1_blank_gage_glass_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_blank_gage_glass_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property AH_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AH_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property AH_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AH_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property alt() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alt", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property alt_glass_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("alt_glass_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property battery_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property battery_cover_mid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_cover_mid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property battery_mid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_mid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property battery_thr_mid() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("battery_thr_mid", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property blank_black() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank_black", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property blank_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property blank_green() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank_green", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property blank_red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank_red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property blank_sq_600px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank_sq_600px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property blank_sq_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank_sq_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property blank_sq_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blank_sq_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property center_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property center_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property center_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property center_4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center_4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property center_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("center_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Compass_2_layer_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Compass_2_layer_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Compass_2_layer_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Compass_2_layer_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property dark_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dark_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property glass_layer_3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("glass_layer_3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_05() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_05", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_06() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_06", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_07() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_07", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_08() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_08", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_09() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_09", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_11() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_11", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_12() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_12", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property needle_13() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("needle_13", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Number_Scroll() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Number_Scroll", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property outside_bg() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outside_bg", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property outside_bg_600() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outside_bg_600", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property outside_bg_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("outside_bg_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Record() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Record", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property SCALE_paul() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SCALE_paul", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property speed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property speed_glass_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speed_glass_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property speed_glowing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("speed_glowing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property StopRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TC_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TC_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TC_bub() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TC_bub", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TC_glass_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TC_glass_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TC_marks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TC_marks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TC_plane() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TC_plane", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property vert_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("vert_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
