'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3615
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class AvionicsInstrumentsControlsRessources
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("HK_GCS.AvionicsInstrumentsControlsRessources", GetType(AvionicsInstrumentsControlsRessources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend Shared ReadOnly Property AirSpeedIndicator_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AirSpeedIndicator_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property AirSpeedNeedle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("AirSpeedNeedle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Altimeter_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Altimeter_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Bandeau_Dérouleur() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bandeau_Dérouleur", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Bandeau_Dérouleur1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bandeau_Dérouleur1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Bandeau_Dérouleur2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Bandeau_Dérouleur2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BatteryBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BatteryCyan() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryCyan", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BatteryGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BatteryIndicator_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryIndicator_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BatteryOrange() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryOrange", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BatteryPurple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryPurple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BatteryRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property BatteryYellow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BatteryYellow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Button() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Button", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property GroundSpeedNeedle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GroundSpeedNeedle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property HeadingIndicator_Aircraft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeadingIndicator_Aircraft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property HeadingIndicator_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeadingIndicator_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property HeadingWeel() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HeadingWeel", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Horizon_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Horizon_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Horizon_GroundSky() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Horizon_GroundSky", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Indicator_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Indicator_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property LongNeedleAltimeter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LongNeedleAltimeter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Maquette_Avion() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Maquette_Avion", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property Record() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Record", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property SmallNeedleAltimeter() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SmallNeedleAltimeter", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property StopRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("StopRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TurnCoordinator_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnCoordinator_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TurnCoordinatorAircraft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnCoordinatorAircraft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TurnCoordinatorBall() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnCoordinatorBall", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property TurnCoordinatorMarks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnCoordinatorMarks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property VerticalSpeedIndicator_Background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VerticalSpeedIndicator_Background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend Shared ReadOnly Property VerticalSpeedNeedle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("VerticalSpeedNeedle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
